### ISSUE TITLE
using Letters in Url

### ISSUE THREAD

**Issue by FTeinz** [baivong/zippy#1]
hallo. I was happy to found your code. but I have some problem when I use letters in the url. for example this url: http://www26.zippyshare.com/v/XVcARUzL/file.html

In my script l would make:

``` javascript
$("#player").zippy({
    www: 26,
    file: XVcARUzL
});
```

But it don't work?!

Could you help

**Comment by lelinhtinh** [comment]
`XVcARUzL` is a string, so it must be kept in quote marks.

``` js
$("#player").zippy({
    www: 26,
    file: "XVcARUzL"
});
```

**Comment by FTeinz** [comment]
omg. Should not code late at night! thanks a lot
Am 17.01.2016 04:37 schrieb Zzbaivong notifications@github.com:XVcARUzL is a string, so it must be kept in quote marks.

$("#player").zippy({
    www: 26,
    file: "XVcARUzL"
});
